//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthVaultProxyTest.HVConnect {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class ConnectRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalPersonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalRecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalPersonName {
            get {
                return LocalPersonNameField;
            }
            set {
                if ((object.ReferenceEquals(LocalPersonNameField, value) != true)) {
                    LocalPersonNameField = value;
                    RaisePropertyChanged("LocalPersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalRecordId {
            get {
                return LocalRecordIdField;
            }
            set {
                if ((object.ReferenceEquals(LocalRecordIdField, value) != true)) {
                    LocalRecordIdField = value;
                    RaisePropertyChanged("LocalRecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretAnswer {
            get {
                return SecretAnswerField;
            }
            set {
                if ((object.ReferenceEquals(SecretAnswerField, value) != true)) {
                    SecretAnswerField = value;
                    RaisePropertyChanged("SecretAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretQuestion {
            get {
                return SecretQuestionField;
            }
            set {
                if ((object.ReferenceEquals(SecretQuestionField, value) != true)) {
                    SecretQuestionField = value;
                    RaisePropertyChanged("SecretQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return TokenField;
            }
            set {
                if ((object.ReferenceEquals(TokenField, value) != true)) {
                    TokenField = value;
                    RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HVProxyResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVConnect.ValidatedConnectionsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVConnect.DeletePendingConnectionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVConnect.ConnectResponse))]
    public partial class HVProxyResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return MessageField;
            }
            set {
                if ((object.ReferenceEquals(MessageField, value) != true)) {
                    MessageField = value;
                    RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stack {
            get {
                return StackField;
            }
            set {
                if ((object.ReferenceEquals(StackField, value) != true)) {
                    StackField = value;
                    RaisePropertyChanged("Stack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return SuccessField;
            }
            set {
                if ((SuccessField.Equals(value) != true)) {
                    SuccessField = value;
                    RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidatedConnectionsResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class ValidatedConnectionsResponse : HealthVaultProxyTest.HVConnect.HVProxyResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HealthVaultProxyTest.HVConnect.ValidatedConnection[] ConnectionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HealthVaultProxyTest.HVConnect.ValidatedConnection[] Connections {
            get {
                return ConnectionsField;
            }
            set {
                if ((object.ReferenceEquals(ConnectionsField, value) != true)) {
                    ConnectionsField = value;
                    RaisePropertyChanged("Connections");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletePendingConnectionResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class DeletePendingConnectionResponse : HealthVaultProxyTest.HVConnect.HVProxyResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevokeApplicationConnectionResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class RevokeApplicationConnectionResponse : HealthVaultProxyTest.HVConnect.HVProxyResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class ConnectResponse : HealthVaultProxyTest.HVConnect.HVProxyResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickupUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionCode {
            get {
                return ConnectionCodeField;
            }
            set {
                if ((object.ReferenceEquals(ConnectionCodeField, value) != true)) {
                    ConnectionCodeField = value;
                    RaisePropertyChanged("ConnectionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupUrl {
            get {
                return PickupUrlField;
            }
            set {
                if ((object.ReferenceEquals(PickupUrlField, value) != true)) {
                    PickupUrlField = value;
                    RaisePropertyChanged("PickupUrl");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidatedConnection", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class ValidatedConnection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationPatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationSpecificRecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RecordIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return ApplicationIdField;
            }
            set {
                if ((ApplicationIdField.Equals(value) != true)) {
                    ApplicationIdField = value;
                    RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationPatientId {
            get {
                return ApplicationPatientIdField;
            }
            set {
                if ((object.ReferenceEquals(ApplicationPatientIdField, value) != true)) {
                    ApplicationPatientIdField = value;
                    RaisePropertyChanged("ApplicationPatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationSpecificRecordId {
            get {
                return ApplicationSpecificRecordIdField;
            }
            set {
                if ((object.ReferenceEquals(ApplicationSpecificRecordIdField, value) != true)) {
                    ApplicationSpecificRecordIdField = value;
                    RaisePropertyChanged("ApplicationSpecificRecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return PersonIdField;
            }
            set {
                if ((PersonIdField.Equals(value) != true)) {
                    PersonIdField = value;
                    RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RecordId {
            get {
                return RecordIdField;
            }
            set {
                if ((RecordIdField.Equals(value) != true)) {
                    RecordIdField = value;
                    RaisePropertyChanged("RecordId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidatedConnectionsRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class ValidatedConnectionsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SinceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SinceDate {
            get {
                return SinceDateField;
            }
            set {
                if ((SinceDateField.Equals(value) != true)) {
                    SinceDateField = value;
                    RaisePropertyChanged("SinceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return TokenField;
            }
            set {
                if ((object.ReferenceEquals(TokenField, value) != true)) {
                    TokenField = value;
                    RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletePendingConnectionRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class DeletePendingConnectionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalRecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalRecordId {
            get {
                return LocalRecordIdField;
            }
            set {
                if ((object.ReferenceEquals(LocalRecordIdField, value) != true)) {
                    LocalRecordIdField = value;
                    RaisePropertyChanged("LocalRecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return TokenField;
            }
            set {
                if ((object.ReferenceEquals(TokenField, value) != true)) {
                    TokenField = value;
                    RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevokeApplicationConnectionRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class RevokeApplicationConnectionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return PersonIdField;
            }
            set {
                if ((PersonIdField.Equals(value) != true)) {
                    PersonIdField = value;
                    RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RecordId {
            get {
                return RecordIdField;
            }
            set {
                if ((RecordIdField.Equals(value) != true)) {
                    RecordIdField = value;
                    RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return TokenField;
            }
            set {
                if ((object.ReferenceEquals(TokenField, value) != true)) {
                    TokenField = value;
                    RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HVConnect.IHVConnect")]
    public interface IHVConnect {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVConnect/CreateConnection", ReplyAction="http://tempuri.org/IHVConnect/CreateConnectionResponse")]
        HealthVaultProxyTest.HVConnect.ConnectResponse CreateConnection(HealthVaultProxyTest.HVConnect.ConnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVConnect/CreateConnection", ReplyAction="http://tempuri.org/IHVConnect/CreateConnectionResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVConnect.ConnectResponse> CreateConnectionAsync(HealthVaultProxyTest.HVConnect.ConnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVConnect/GetValidatedConnections", ReplyAction="http://tempuri.org/IHVConnect/GetValidatedConnectionsResponse")]
        HealthVaultProxyTest.HVConnect.ValidatedConnectionsResponse GetValidatedConnections(HealthVaultProxyTest.HVConnect.ValidatedConnectionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVConnect/GetValidatedConnections", ReplyAction="http://tempuri.org/IHVConnect/GetValidatedConnectionsResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVConnect.ValidatedConnectionsResponse> GetValidatedConnectionsAsync(HealthVaultProxyTest.HVConnect.ValidatedConnectionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVConnect/DeletePendingConnection", ReplyAction="http://tempuri.org/IHVConnect/DeletePendingConnectionResponse")]
        HealthVaultProxyTest.HVConnect.DeletePendingConnectionResponse DeletePendingConnection(HealthVaultProxyTest.HVConnect.DeletePendingConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVConnect/DeletePendingConnection", ReplyAction="http://tempuri.org/IHVConnect/DeletePendingConnectionResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVConnect.DeletePendingConnectionResponse> DeletePendingConnectionAsync(HealthVaultProxyTest.HVConnect.DeletePendingConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVConnect/RevokeApplicationConnection", ReplyAction="http://tempuri.org/IHVConnect/RevokeApplicationConnectionResponse")]
        HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionResponse RevokeApplicationConnection(HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVConnect/RevokeApplicationConnection", ReplyAction="http://tempuri.org/IHVConnect/RevokeApplicationConnectionResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionResponse> RevokeApplicationConnectionAsync(HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHVConnectChannel : HealthVaultProxyTest.HVConnect.IHVConnect, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HVConnectClient : System.ServiceModel.ClientBase<HealthVaultProxyTest.HVConnect.IHVConnect>, HealthVaultProxyTest.HVConnect.IHVConnect {
        
        public HVConnectClient() {
        }
        
        public HVConnectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HVConnectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HVConnectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HVConnectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HealthVaultProxyTest.HVConnect.ConnectResponse CreateConnection(HealthVaultProxyTest.HVConnect.ConnectRequest request) {
            return base.Channel.CreateConnection(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVConnect.ConnectResponse> CreateConnectionAsync(HealthVaultProxyTest.HVConnect.ConnectRequest request) {
            return base.Channel.CreateConnectionAsync(request);
        }
        
        public HealthVaultProxyTest.HVConnect.ValidatedConnectionsResponse GetValidatedConnections(HealthVaultProxyTest.HVConnect.ValidatedConnectionsRequest request) {
            return base.Channel.GetValidatedConnections(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVConnect.ValidatedConnectionsResponse> GetValidatedConnectionsAsync(HealthVaultProxyTest.HVConnect.ValidatedConnectionsRequest request) {
            return base.Channel.GetValidatedConnectionsAsync(request);
        }
        
        public HealthVaultProxyTest.HVConnect.DeletePendingConnectionResponse DeletePendingConnection(HealthVaultProxyTest.HVConnect.DeletePendingConnectionRequest request) {
            return base.Channel.DeletePendingConnection(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVConnect.DeletePendingConnectionResponse> DeletePendingConnectionAsync(HealthVaultProxyTest.HVConnect.DeletePendingConnectionRequest request) {
            return base.Channel.DeletePendingConnectionAsync(request);
        }
        
        public HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionResponse RevokeApplicationConnection(HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionRequest request) {
            return base.Channel.RevokeApplicationConnection(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionResponse> RevokeApplicationConnectionAsync(HealthVaultProxyTest.HVConnect.RevokeApplicationConnectionRequest request) {
            return base.Channel.RevokeApplicationConnectionAsync(request);
        }
    }
}
