//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthVaultProxyTest.HVDataAccess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUpdatedRecordsRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class GetUpdatedRecordsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SinceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SinceDate {
            get {
                return this.SinceDateField;
            }
            set {
                if ((this.SinceDateField.Equals(value) != true)) {
                    this.SinceDateField = value;
                    this.RaisePropertyChanged("SinceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HVProxyResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVDataAccess.GetThingsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVDataAccess.PutThingResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVDataAccess.PutThingsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsResponse))]
    public partial class HVProxyResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stack {
            get {
                return this.StackField;
            }
            set {
                if ((object.ReferenceEquals(this.StackField, value) != true)) {
                    this.StackField = value;
                    this.RaisePropertyChanged("Stack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetThingsResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class GetThingsResponse : HealthVaultProxyTest.HVDataAccess.HVProxyResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ThingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Things {
            get {
                return this.ThingsField;
            }
            set {
                if ((object.ReferenceEquals(this.ThingsField, value) != true)) {
                    this.ThingsField = value;
                    this.RaisePropertyChanged("Things");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PutThingResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class PutThingResponse : HealthVaultProxyTest.HVDataAccess.HVProxyResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PutThingsResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class PutThingsResponse : HealthVaultProxyTest.HVDataAccess.HVProxyResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountSucceededField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexOnErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountReceived {
            get {
                return this.CountReceivedField;
            }
            set {
                if ((this.CountReceivedField.Equals(value) != true)) {
                    this.CountReceivedField = value;
                    this.RaisePropertyChanged("CountReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountSucceeded {
            get {
                return this.CountSucceededField;
            }
            set {
                if ((this.CountSucceededField.Equals(value) != true)) {
                    this.CountSucceededField = value;
                    this.RaisePropertyChanged("CountSucceeded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndexOnError {
            get {
                return this.IndexOnErrorField;
            }
            set {
                if ((this.IndexOnErrorField.Equals(value) != true)) {
                    this.IndexOnErrorField = value;
                    this.RaisePropertyChanged("IndexOnError");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUpdatedRecordsResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class GetUpdatedRecordsResponse : HealthVaultProxyTest.HVDataAccess.HVProxyResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HealthVaultProxyTest.HVDataAccess.RecordUpdateInfo[] UpdatedRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HealthVaultProxyTest.HVDataAccess.RecordUpdateInfo[] UpdatedRecords {
            get {
                return this.UpdatedRecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedRecordsField, value) != true)) {
                    this.UpdatedRecordsField = value;
                    this.RaisePropertyChanged("UpdatedRecords");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordUpdateInfo", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class RecordUpdateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RecordIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDate {
            get {
                return this.LastUpdateDateField;
            }
            set {
                if ((this.LastUpdateDateField.Equals(value) != true)) {
                    this.LastUpdateDateField = value;
                    this.RaisePropertyChanged("LastUpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((this.RecordIdField.Equals(value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetThingsRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class GetThingsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SinceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] TypeIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((this.RecordIdField.Equals(value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SinceDate {
            get {
                return this.SinceDateField;
            }
            set {
                if ((this.SinceDateField.Equals(value) != true)) {
                    this.SinceDateField = value;
                    this.RaisePropertyChanged("SinceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] TypeIds {
            get {
                return this.TypeIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeIdsField, value) != true)) {
                    this.TypeIdsField = value;
                    this.RaisePropertyChanged("TypeIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PutThingRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class PutThingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((this.RecordIdField.Equals(value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlItem {
            get {
                return this.XmlItemField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlItemField, value) != true)) {
                    this.XmlItemField = value;
                    this.RaisePropertyChanged("XmlItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PutThingsRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class PutThingsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] XmlInputsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((this.RecordIdField.Equals(value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] XmlInputs {
            get {
                return this.XmlInputsField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlInputsField, value) != true)) {
                    this.XmlInputsField = value;
                    this.RaisePropertyChanged("XmlInputs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HVDataAccess.IHVDataAccess")]
    public interface IHVDataAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDataAccess/GetUpdatedRecords", ReplyAction="http://tempuri.org/IHVDataAccess/GetUpdatedRecordsResponse")]
        HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsResponse GetUpdatedRecords(HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDataAccess/GetUpdatedRecords", ReplyAction="http://tempuri.org/IHVDataAccess/GetUpdatedRecordsResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsResponse> GetUpdatedRecordsAsync(HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDataAccess/GetThings", ReplyAction="http://tempuri.org/IHVDataAccess/GetThingsResponse")]
        HealthVaultProxyTest.HVDataAccess.GetThingsResponse GetThings(HealthVaultProxyTest.HVDataAccess.GetThingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDataAccess/GetThings", ReplyAction="http://tempuri.org/IHVDataAccess/GetThingsResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDataAccess.GetThingsResponse> GetThingsAsync(HealthVaultProxyTest.HVDataAccess.GetThingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDataAccess/PutThing", ReplyAction="http://tempuri.org/IHVDataAccess/PutThingResponse")]
        HealthVaultProxyTest.HVDataAccess.PutThingResponse PutThing(HealthVaultProxyTest.HVDataAccess.PutThingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDataAccess/PutThing", ReplyAction="http://tempuri.org/IHVDataAccess/PutThingResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDataAccess.PutThingResponse> PutThingAsync(HealthVaultProxyTest.HVDataAccess.PutThingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDataAccess/PutThings", ReplyAction="http://tempuri.org/IHVDataAccess/PutThingsResponse")]
        HealthVaultProxyTest.HVDataAccess.PutThingsResponse PutThings(HealthVaultProxyTest.HVDataAccess.PutThingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDataAccess/PutThings", ReplyAction="http://tempuri.org/IHVDataAccess/PutThingsResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDataAccess.PutThingsResponse> PutThingsAsync(HealthVaultProxyTest.HVDataAccess.PutThingsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHVDataAccessChannel : HealthVaultProxyTest.HVDataAccess.IHVDataAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HVDataAccessClient : System.ServiceModel.ClientBase<HealthVaultProxyTest.HVDataAccess.IHVDataAccess>, HealthVaultProxyTest.HVDataAccess.IHVDataAccess {
        
        public HVDataAccessClient() {
        }
        
        public HVDataAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HVDataAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HVDataAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HVDataAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsResponse GetUpdatedRecords(HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsRequest request) {
            return base.Channel.GetUpdatedRecords(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsResponse> GetUpdatedRecordsAsync(HealthVaultProxyTest.HVDataAccess.GetUpdatedRecordsRequest request) {
            return base.Channel.GetUpdatedRecordsAsync(request);
        }
        
        public HealthVaultProxyTest.HVDataAccess.GetThingsResponse GetThings(HealthVaultProxyTest.HVDataAccess.GetThingsRequest request) {
            return base.Channel.GetThings(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDataAccess.GetThingsResponse> GetThingsAsync(HealthVaultProxyTest.HVDataAccess.GetThingsRequest request) {
            return base.Channel.GetThingsAsync(request);
        }
        
        public HealthVaultProxyTest.HVDataAccess.PutThingResponse PutThing(HealthVaultProxyTest.HVDataAccess.PutThingRequest request) {
            return base.Channel.PutThing(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDataAccess.PutThingResponse> PutThingAsync(HealthVaultProxyTest.HVDataAccess.PutThingRequest request) {
            return base.Channel.PutThingAsync(request);
        }
        
        public HealthVaultProxyTest.HVDataAccess.PutThingsResponse PutThings(HealthVaultProxyTest.HVDataAccess.PutThingsRequest request) {
            return base.Channel.PutThings(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDataAccess.PutThingsResponse> PutThingsAsync(HealthVaultProxyTest.HVDataAccess.PutThingsRequest request) {
            return base.Channel.PutThingsAsync(request);
        }
    }
}
