//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthVaultProxyTest.HVDropOff {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HVProxyResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVDropOff.DropOffResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HealthVaultProxyTest.HVDropOff.PreAllocatePackageIdResponse))]
    public partial class HVProxyResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return MessageField;
            }
            set {
                if ((object.ReferenceEquals(MessageField, value) != true)) {
                    MessageField = value;
                    RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stack {
            get {
                return StackField;
            }
            set {
                if ((object.ReferenceEquals(StackField, value) != true)) {
                    StackField = value;
                    RaisePropertyChanged("Stack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return SuccessField;
            }
            set {
                if ((SuccessField.Equals(value) != true)) {
                    SuccessField = value;
                    RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DropOffResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class DropOffResponse : HealthVaultProxyTest.HVDropOff.HVProxyResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickupUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupUrl {
            get {
                return PickupUrlField;
            }
            set {
                if ((object.ReferenceEquals(PickupUrlField, value) != true)) {
                    PickupUrlField = value;
                    RaisePropertyChanged("PickupUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretCode {
            get {
                return SecretCodeField;
            }
            set {
                if ((object.ReferenceEquals(SecretCodeField, value) != true)) {
                    SecretCodeField = value;
                    RaisePropertyChanged("SecretCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreAllocatePackageIdResponse", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class PreAllocatePackageIdResponse : HealthVaultProxyTest.HVDropOff.HVProxyResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DopuPackageIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DopuPackageId {
            get {
                return DopuPackageIdField;
            }
            set {
                if ((object.ReferenceEquals(DopuPackageIdField, value) != true)) {
                    DopuPackageIdField = value;
                    RaisePropertyChanged("DopuPackageId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DropOffRequest", Namespace="http://schemas.datacontract.org/2004/07/HealthVaultProxy")]
    [System.SerializableAttribute()]
    public partial class DropOffRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DopuPackageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] EmailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalPatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ThingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DopuPackageId {
            get {
                return DopuPackageIdField;
            }
            set {
                if ((object.ReferenceEquals(DopuPackageIdField, value) != true)) {
                    DopuPackageIdField = value;
                    RaisePropertyChanged("DopuPackageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailFrom {
            get {
                return EmailFromField;
            }
            set {
                if ((object.ReferenceEquals(EmailFromField, value) != true)) {
                    EmailFromField = value;
                    RaisePropertyChanged("EmailFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailSubject {
            get {
                return EmailSubjectField;
            }
            set {
                if ((object.ReferenceEquals(EmailSubjectField, value) != true)) {
                    EmailSubjectField = value;
                    RaisePropertyChanged("EmailSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] EmailTo {
            get {
                return EmailToField;
            }
            set {
                if ((object.ReferenceEquals(EmailToField, value) != true)) {
                    EmailToField = value;
                    RaisePropertyChanged("EmailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromName {
            get {
                return FromNameField;
            }
            set {
                if ((object.ReferenceEquals(FromNameField, value) != true)) {
                    FromNameField = value;
                    RaisePropertyChanged("FromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalPatientId {
            get {
                return LocalPatientIdField;
            }
            set {
                if ((object.ReferenceEquals(LocalPatientIdField, value) != true)) {
                    LocalPatientIdField = value;
                    RaisePropertyChanged("LocalPatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretAnswer {
            get {
                return SecretAnswerField;
            }
            set {
                if ((object.ReferenceEquals(SecretAnswerField, value) != true)) {
                    SecretAnswerField = value;
                    RaisePropertyChanged("SecretAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretQuestion {
            get {
                return SecretQuestionField;
            }
            set {
                if ((object.ReferenceEquals(SecretQuestionField, value) != true)) {
                    SecretQuestionField = value;
                    RaisePropertyChanged("SecretQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Things {
            get {
                return ThingsField;
            }
            set {
                if ((object.ReferenceEquals(ThingsField, value) != true)) {
                    ThingsField = value;
                    RaisePropertyChanged("Things");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return TokenField;
            }
            set {
                if ((object.ReferenceEquals(TokenField, value) != true)) {
                    TokenField = value;
                    RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HVDropOff.IHVDropOff")]
    public interface IHVDropOff {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/PreAllocatePackageId", ReplyAction="http://tempuri.org/IHVDropOff/PreAllocatePackageIdResponse")]
        HealthVaultProxyTest.HVDropOff.PreAllocatePackageIdResponse PreAllocatePackageId(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/PreAllocatePackageId", ReplyAction="http://tempuri.org/IHVDropOff/PreAllocatePackageIdResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.PreAllocatePackageIdResponse> PreAllocatePackageIdAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/DropOffForPatient", ReplyAction="http://tempuri.org/IHVDropOff/DropOffForPatientResponse")]
        HealthVaultProxyTest.HVDropOff.DropOffResponse DropOffForPatient(HealthVaultProxyTest.HVDropOff.DropOffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/DropOffForPatient", ReplyAction="http://tempuri.org/IHVDropOff/DropOffForPatientResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.DropOffResponse> DropOffForPatientAsync(HealthVaultProxyTest.HVDropOff.DropOffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/DropOffForPackageId", ReplyAction="http://tempuri.org/IHVDropOff/DropOffForPackageIdResponse")]
        HealthVaultProxyTest.HVDropOff.DropOffResponse DropOffForPackageId(HealthVaultProxyTest.HVDropOff.DropOffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/DropOffForPackageId", ReplyAction="http://tempuri.org/IHVDropOff/DropOffForPackageIdResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.DropOffResponse> DropOffForPackageIdAsync(HealthVaultProxyTest.HVDropOff.DropOffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/DeletePendingForPatient", ReplyAction="http://tempuri.org/IHVDropOff/DeletePendingForPatientResponse")]
        HealthVaultProxyTest.HVDropOff.HVProxyResponse DeletePendingForPatient(string Token, string LocalPatientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/DeletePendingForPatient", ReplyAction="http://tempuri.org/IHVDropOff/DeletePendingForPatientResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.HVProxyResponse> DeletePendingForPatientAsync(string Token, string LocalPatientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/DeletePendingForPackageId", ReplyAction="http://tempuri.org/IHVDropOff/DeletePendingForPackageIdResponse")]
        HealthVaultProxyTest.HVDropOff.HVProxyResponse DeletePendingForPackageId(string Token, string DopuPackageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHVDropOff/DeletePendingForPackageId", ReplyAction="http://tempuri.org/IHVDropOff/DeletePendingForPackageIdResponse")]
        System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.HVProxyResponse> DeletePendingForPackageIdAsync(string Token, string DopuPackageId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHVDropOffChannel : HealthVaultProxyTest.HVDropOff.IHVDropOff, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HVDropOffClient : System.ServiceModel.ClientBase<HealthVaultProxyTest.HVDropOff.IHVDropOff>, HealthVaultProxyTest.HVDropOff.IHVDropOff {
        
        public HVDropOffClient() {
        }
        
        public HVDropOffClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HVDropOffClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HVDropOffClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HVDropOffClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HealthVaultProxyTest.HVDropOff.PreAllocatePackageIdResponse PreAllocatePackageId(string token) {
            return base.Channel.PreAllocatePackageId(token);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.PreAllocatePackageIdResponse> PreAllocatePackageIdAsync(string token) {
            return base.Channel.PreAllocatePackageIdAsync(token);
        }
        
        public HealthVaultProxyTest.HVDropOff.DropOffResponse DropOffForPatient(HealthVaultProxyTest.HVDropOff.DropOffRequest request) {
            return base.Channel.DropOffForPatient(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.DropOffResponse> DropOffForPatientAsync(HealthVaultProxyTest.HVDropOff.DropOffRequest request) {
            return base.Channel.DropOffForPatientAsync(request);
        }
        
        public HealthVaultProxyTest.HVDropOff.DropOffResponse DropOffForPackageId(HealthVaultProxyTest.HVDropOff.DropOffRequest request) {
            return base.Channel.DropOffForPackageId(request);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.DropOffResponse> DropOffForPackageIdAsync(HealthVaultProxyTest.HVDropOff.DropOffRequest request) {
            return base.Channel.DropOffForPackageIdAsync(request);
        }
        
        public HealthVaultProxyTest.HVDropOff.HVProxyResponse DeletePendingForPatient(string Token, string LocalPatientId) {
            return base.Channel.DeletePendingForPatient(Token, LocalPatientId);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.HVProxyResponse> DeletePendingForPatientAsync(string Token, string LocalPatientId) {
            return base.Channel.DeletePendingForPatientAsync(Token, LocalPatientId);
        }
        
        public HealthVaultProxyTest.HVDropOff.HVProxyResponse DeletePendingForPackageId(string Token, string DopuPackageId) {
            return base.Channel.DeletePendingForPackageId(Token, DopuPackageId);
        }
        
        public System.Threading.Tasks.Task<HealthVaultProxyTest.HVDropOff.HVProxyResponse> DeletePendingForPackageIdAsync(string Token, string DopuPackageId) {
            return base.Channel.DeletePendingForPackageIdAsync(Token, DopuPackageId);
        }
    }
}
